### ISSUE TITLE
Check on Macs

### ISSUE THREAD

**Issue by paireks** [paireks/Pterodactyl#29]

**Comment by dilomo** [comment]
![image](https://user-images.githubusercontent.com/62781182/217854130-4430510e-13b7-4e4c-b2b0-8bedd06e842c.png)

The text must be removed on mac as it does not update properly and Esc does not work

**Comment by dilomo** [comment]
Also Y axis text is at angle when vertical

**Comment by dilomo** [comment]
![tesAdvancedChart](https://user-images.githubusercontent.com/62781182/217855371-298953c8-cb08-4381-acc2-b8590cf3bd28.png)
![tesViewport](https://user-images.githubusercontent.com/62781182/217855375-0a83f43e-435b-44de-acaf-5a8ee947caf2.png)
![tesPointGraph](https://user-images.githubusercontent.com/62781182/217855376-293e6a3a-6403-4763-8d49-2adc49076617.png)
![tesPieChart](https://user-images.githubusercontent.com/62781182/217855378-cafe4b17-517f-49ef-9a9e-c6df26587f6f.png)
![tesLineGraph](https://user-images.githubusercontent.com/62781182/217855381-75fc2f16-e6f2-4692-981b-c9f647f15b67.png)
![tesColumnChart](https://user-images.githubusercontent.com/62781182/217855383-b1955916-a0bd-4492-8077-f84b03864a57.png)
![tesBarChart](https://user-images.githubusercontent.com/62781182/217855385-c1cbfe5d-be78-4380-a941-ec49a4f3e787.png)
